import { mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { normalizeIconName, pascalToSnake, toPascalCase } from './naming.js';
import type { IconRegistryFile, IconStyle } from './types.js';

type StyleDataMap = Partial<Record<IconStyle, IconRegistryFile>>;

const STYLES: IconStyle[] = ['rounded', 'outlined', 'sharp'];

const toPathsObject = (styleData: StyleDataMap): string => {
  const blocks = STYLES.filter((style) => Boolean(styleData[style])).map((style) => {
    const data = styleData[style]!;
    return `  ${style}: {\n    fill0: ${JSON.stringify(data.paths.fill0)},\n    fill1: ${JSON.stringify(data.paths.fill1)},\n  },`;
  });
  return blocks.join('\n');
};

const toStyleUnion = (styleData: StyleDataMap): string => {
  const styles = STYLES.filter((style) => Boolean(styleData[style]));
  return styles.map((style) => `'${style}'`).join(' | ');
};

const defaultStyleFor = (styleData: StyleDataMap): IconStyle => {
  if (styleData.rounded) {
    return 'rounded';
  }
  if (styleData.outlined) {
    return 'outlined';
  }
  return 'sharp';
};

const renderComponentSource = (iconName: string, styleData: StyleDataMap): string => {
  const componentName = toPascalCase(iconName);
  const availableStyleUnion = toStyleUnion(styleData);
  const defaultStyle = defaultStyleFor(styleData);
  const pathsObject = toPathsObject(styleData);

  return `// Generated by rh-mi-cli - run 'npx rh-mi update ${iconName}' to refresh\n// Icon: ${iconName}\n\nimport { SvgIcon } from 'rh-mi-react'\nimport type { IconProps } from 'rh-mi-react'\n\nconst PATHS = {\n${pathsObject}\n} as const\n\ntype AvailableStyle = ${availableStyleUnion}\n\nconst resolveStyle = (input: IconProps['iconStyle']): AvailableStyle => {\n  if (!input) {\n    return '${defaultStyle}'\n  }\n  return (input in PATHS ? input : '${defaultStyle}') as AvailableStyle\n}\n\nconst resolveFill = (input: IconProps['fill']): 'fill0' | 'fill1' => {\n  return input === 1 ? 'fill1' : 'fill0'\n}\n\nexport const ${componentName} = ({ iconStyle = '${defaultStyle}', fill = 0, ...rest }: IconProps) => {\n  const styleKey = resolveStyle(iconStyle)\n  const fillKey = resolveFill(fill)\n\n  return <SvgIcon {...rest} iconStyle={styleKey} fill={fill === 1 ? 1 : 0} pathData={PATHS[styleKey][fillKey]} iconName='${iconName}' />\n}\n`;
};

const iconFilePath = (iconsDir: string, iconName: string): string => {
  return path.join(iconsDir, `${toPascalCase(iconName)}.tsx`);
};

const absoluteIconsDir = (cwd: string, iconsDir: string): string => path.resolve(cwd, iconsDir);

export const ensureIconsDirectory = async (cwd: string, iconsDir: string): Promise<string> => {
  const absolute = absoluteIconsDir(cwd, iconsDir);
  await mkdir(absolute, { recursive: true });
  return absolute;
};

export const writeIconComponent = async (
  cwd: string,
  iconsDir: string,
  iconName: string,
  styleData: StyleDataMap,
): Promise<string> => {
  const normalized = normalizeIconName(iconName);
  const absoluteDir = await ensureIconsDirectory(cwd, iconsDir);
  const target = iconFilePath(absoluteDir, normalized);
  const content = renderComponentSource(normalized, styleData);
  await writeFile(target, content, 'utf8');
  return target;
};

export const removeIconComponent = async (cwd: string, iconsDir: string, iconName: string): Promise<boolean> => {
  const absoluteDir = absoluteIconsDir(cwd, iconsDir);
  const target = iconFilePath(absoluteDir, normalizeIconName(iconName));
  try {
    await rm(target);
    return true;
  } catch {
    return false;
  }
};

const readIconNameFromFile = async (absolutePath: string): Promise<string> => {
  const raw = await readFile(absolutePath, 'utf8');
  const fromComment = raw.match(/^\/\/ Icon: ([a-z0-9_]+)/m)?.[1];
  if (fromComment) {
    return fromComment;
  }
  const base = path.basename(absolutePath, '.tsx');
  return pascalToSnake(base);
};

export const listInstalledIcons = async (cwd: string, iconsDir: string): Promise<string[]> => {
  const absoluteDir = absoluteIconsDir(cwd, iconsDir);
  try {
    const dirStat = await stat(absoluteDir);
    if (!dirStat.isDirectory()) {
      return [];
    }
  } catch {
    return [];
  }

  const files = await readdir(absoluteDir);
  const iconFiles = files.filter((file) => file.endsWith('.tsx') && file !== 'index.ts');
  const names = await Promise.all(iconFiles.map((file) => readIconNameFromFile(path.join(absoluteDir, file))));
  return names.sort();
};

export const updateBarrelFile = async (cwd: string, iconsDir: string): Promise<string> => {
  const absoluteDir = await ensureIconsDirectory(cwd, iconsDir);
  const files = await readdir(absoluteDir);
  const exports = files
    .filter((file) => file.endsWith('.tsx') && file !== 'index.ts')
    .map((file) => path.basename(file, '.tsx'))
    .sort((a, b) => a.localeCompare(b))
    .map((name) => `export { ${name} } from './${name}'`);

  const content = exports.length > 0 ? `${exports.join('\n')}\n` : '';
  const barrelPath = path.join(absoluteDir, 'index.ts');
  await writeFile(barrelPath, content, 'utf8');
  return barrelPath;
};

